// miniApp/src/widgets/BusSchedule/ui/BusSchedule.tsx
import { busDirectionType } from "@/entities/busRoute";
import { GetBusSchedule } from "@/features/getBusSchedule";
import { Filter } from "@/shared/ui/Filter/Filter";
import cls from './BusSchedule.module.css';
import { useMemo, useState } from "react";

export const BusSchedule = () => {
    const [direction, setDirection] = useState<busDirectionType>('toEkb');
    
    console.log(direction)

    const tabsArray = useMemo(() => [
        {
            name: 'Полевской -> Екб',
            activeStatus: direction === 'toEkb',
            onClick: () => setDirection('toEkb')
        },
        {
            name: 'Екб -> Полевской',
            activeStatus: direction === 'toPolevskoy',
            onClick: () => setDirection('toPolevskoy')
        }
    ], [direction])

    return (
        <div className={cls.BusSchedule}>
            <h2 className={cls.heading}>Расписание автобусов</h2>
            <Filter title="" tabs={tabsArray} className={cls.filtres}/>
            <GetBusSchedule direction={direction}/>
        </div>
    );
};

// mini-app-vue/src/widgets/BusSchedule/ui/BusSchedule.vue
<template>
  <div :class="cls.BusSchedule">
    <h2 :class="cls.heading">Расписание автобусов</h2>
    <Filter :title="''" :tabs="tabsArray" :class="cls.filtres" />
    <GetBusSchedule :direction="direction" />
  </div>
</template>

<script>
import { ref, computed } from "vue";
import GetBusSchedule from "@/features/getBusSchedule";
import Filter from "@/shared/ui/Filter/Filter";
import cls from "./BusSchedule.module.css";

export default {
  name: "BusSchedule",
  components: {
    GetBusSchedule,
    Filter,
  },
  computed: {
    cls() {
      return cls;
    },
  },
  setup() {
    const direction = ref("toEkb");

    const tabsArray = computed(() => [
      {
        name: "Полевской -> Екб",
        activeStatus: direction.value === "toEkb",
        onClick: () => (direction.value = "toEkb"),
      },
      {
        name: "Екб -> Полевской",
        activeStatus: direction.value === "toPolevskoy",
        onClick: () => (direction.value = "toPolevskoy"),
      },
    ]);

    return {
      direction,
      tabsArray,
    };
  },
};
</script>
