// mini-app-vue/src/pages/NotFoundPage/ui/NotFoundPage.vue
<template>
  <div>Страница не найдена</div>
</template>

<script>
import { ref, onMounted, onBeforeUnmount } from "vue";
import { useRouter } from "vue-router";

export default {
  name: "NotFoundPage",
  setup() {
    const router = useRouter();
    const redirectTimer = ref(null);

    onMounted(() => {
      redirectTimer.value = setTimeout(() => {
        router.push({ name: "MainPage" });
      }, 2000);
    });

    onBeforeUnmount(() => {
      clearTimeout(redirectTimer.value);
    });
  },
};
</script>

// frontend/src/pages/NotFoundPage/ui/NotFoundPage.tsx
import { RoutePath } from "@/shared/config/routerConfig/routerConfig";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";

const NotFoundPage = () => {
    const navigate = useNavigate();

    useEffect(() => {
        const redirectTimer = setTimeout(() => {
            navigate(RoutePath.main);
        }, 2000);
    
        return () => clearTimeout(redirectTimer);
    }, [navigate]);

    return (
        <div>
            Страница не найдена
        </div>
    );
};

export default NotFoundPage;
