// mini-app-vue/src/entities/busRoute/ui/busRoute/BusRoute.vue
<template>
  <div>
    <BusRouteToEkb v-if="route.busDirection === 'toEkb'" :route="route" />
    <BusRouteToPolevskoy
      v-else-if="route.busDirection === 'toPolevskoy'"
      :route="route"
    />
  </div>
</template>

<script lang="ts">
import { PropType } from "vue";
import {
  busRouteToEkbType,
  busRouteToPolevskoyType,
} from "../../model/types/types";
import BusRouteToPolevskoy from "../busRouteToPolevskoy/BusRouteToPolevskoy.vue";
import BusRouteToEkb from "../busRouteToEkb/BusRouteToEkb.vue";

export default {
  name: "BusRoute",
  components: {
    BusRouteToPolevskoy,
    BusRouteToEkb,
  },
  props: {
    route: {
      type: Object as PropType<busRouteToEkbType | busRouteToPolevskoyType>,
      required: true,
    },
  },
};
</script>

// miniApp/src/entities/busRoute/ui/busRoute/busRoute.tsx
import { busRouteToEkbType, busRouteToPolevskoyType } from '../../model/types/types';
import { BusRouteToPolevskoy } from '../busRouteToPolevskoy/busRouteToPolevskoy';
import { BusRouteToEkb } from '../butRouteToEkb/butRouteToEkb';

interface busRouteProps {
    route: busRouteToEkbType | busRouteToPolevskoyType
}

export const BusRoute = ({route}: busRouteProps) => {
    switch (route.busDirection) {
        case 'toEkb':
            return <BusRouteToEkb route={route}/>
        case 'toPolevskoy':
            return <BusRouteToPolevskoy route={route} />
    }
};
